/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.prog4.isc.GestorProyectos.UI;

import co.edu.utp.prog4.isc.GestorProyectos.Controladores.ActividadesJpaController;
import co.edu.utp.prog4.isc.GestorProyectos.Controladores.AsignadasJpaController;
import co.edu.utp.prog4.isc.GestorProyectos.Controladores.TareasJpaController;
import co.edu.utp.prog4.isc.GestorProyectos.Controladores.UsuariosJpaController;
import co.edu.utp.prog4.isc.GestorProyectos.Modelo.Asignadas;
import co.edu.utp.prog4.isc.GestorProyectos.Modelo.Roles;
import co.edu.utp.prog4.isc.GestorProyectos.Modelo.Tareas;
import co.edu.utp.prog4.isc.GestorProyectos.Modelo.Usuarios;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ANDRES
 */
public class GestorProyectos extends javax.swing.JFrame {

    /**
     * Creates new form GestorProyectos
     */
    private UsuariosJpaController CUsuarios;
    private TareasJpaController CTareas;
    private ActividadesJpaController CActividades;
    private AsignadasJpaController CAsignadas;
    private int rol;
   
    public GestorProyectos() {
        initComponents();
        CUsuarios = new UsuariosJpaController();
        CTareas = new TareasJpaController();
        CActividades = new ActividadesJpaController();
        CAsignadas = new AsignadasJpaController();
        cargarComboBox();
        this.setLocationRelativeTo(null);
        this.setSize(500, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        PanelLogin = new javax.swing.JPanel();
        FormularioIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CampoUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        InterfazAdministrador = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelOpciones = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Opciones = new javax.swing.JPanel();
        Opciones2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Salir = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        AsignarTarea = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PanelRegreso = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        PanelCreacion = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        barraUsuarios = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        barraTareas = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        PanelLogin.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Usuario : ");
        FormularioIngreso.add(jLabel1);

        CampoUsuario.setPreferredSize(new java.awt.Dimension(100, 25));
        FormularioIngreso.add(CampoUsuario);

        jLabel2.setText("Password : ");
        FormularioIngreso.add(jLabel2);

        CampoPassword.setPreferredSize(new java.awt.Dimension(100, 25));
        CampoPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPasswordActionPerformed(evt);
            }
        });
        FormularioIngreso.add(CampoPassword);

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        FormularioIngreso.add(jButton1);

        PanelLogin.add(FormularioIngreso, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(PanelLogin, "card2");

        InterfazAdministrador.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Interfaz administrador");
        InterfazAdministrador.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        PanelOpciones.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Opciones");
        PanelOpciones.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        Opciones.setLayout(new java.awt.BorderLayout());

        jButton6.setText("Crear tarea");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Opciones2.add(jButton6);

        jButton4.setText("Asignar tarea");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Opciones2.add(jButton4);

        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Opciones2.add(jButton5);

        Opciones.add(Opciones2, java.awt.BorderLayout.PAGE_END);

        PanelOpciones.add(Opciones, java.awt.BorderLayout.CENTER);

        InterfazAdministrador.add(PanelOpciones, java.awt.BorderLayout.CENTER);

        Salir.setLayout(new java.awt.BorderLayout());

        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        Salir.add(jButton3, java.awt.BorderLayout.LINE_END);

        InterfazAdministrador.add(Salir, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(InterfazAdministrador, "card3");

        AsignarTarea.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Asignacion de tareas");
        AsignarTarea.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        PanelRegreso.setLayout(new java.awt.BorderLayout());

        jButton7.setText("Regresar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton7MouseReleased(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        PanelRegreso.add(jButton7, java.awt.BorderLayout.LINE_END);

        jPanel1.add(PanelRegreso, java.awt.BorderLayout.PAGE_END);

        PanelCreacion.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Usuario ");
        jPanel2.add(jLabel6);

        barraUsuarios.setMaximumRowCount(100);
        jPanel2.add(barraUsuarios);

        jLabel7.setText("Tarea");
        jPanel2.add(jLabel7);

        barraTareas.setMaximumRowCount(100);
        jPanel2.add(barraTareas);

        PanelCreacion.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jButton9.setText("Confirmar Asignacion");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton9MouseReleased(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, java.awt.BorderLayout.LINE_END);

        PanelCreacion.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(PanelCreacion, java.awt.BorderLayout.CENTER);

        AsignarTarea.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(AsignarTarea, "card4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPasswordActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        Roles rol = null;
        rol = login(CampoUsuario.getText(),CampoPassword.getText());
        if(rol == null){
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña invalidos");
        }
        else{
            if(rol.getIdRol()==1){
                CampoUsuario.setText("");
                CampoPassword.setText("");
                JOptionPane.showMessageDialog(null, "Ingreso de administrador");
                PanelLogin.setVisible(false);
                this.setSize(500, 150);
                InterfazAdministrador.setVisible(true);
            }
            if(rol.getIdRol()==2){
                JOptionPane.showMessageDialog(null, "Ingreso de ususario");
            }
        }
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        InterfazAdministrador.setVisible(false);
        PanelLogin.setVisible(true);
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseReleased
        InterfazAdministrador.setVisible(false);
        this.setSize(400, 150);
        AsignarTarea.setVisible(true);
    }//GEN-LAST:event_jButton4MouseReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseReleased
        AsignarTarea.setVisible(false);
        InterfazAdministrador.setVisible(true);
        this.setSize(500, 150);
    }//GEN-LAST:event_jButton7MouseReleased

    private void jButton9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseReleased
        try {
            Asignadas asignada = new Asignadas();
            List<Usuarios> usuarios = CUsuarios.findUsuariosEntities();
            Usuarios encontrado = null;
            for(Usuarios i : usuarios){
                if(((String)barraUsuarios.getSelectedItem()).equals(i.getUsuario())){
                    encontrado = i;
                    break;
                }
            }
            asignada.setUsuarios(encontrado);
            List<Tareas> tareas = CTareas.findTareasEntities();
            Tareas encontrado2 = null;
            for(Tareas i : tareas){
                if(((String)barraTareas.getSelectedItem()).equals(i.getDescripcion())){
                    encontrado2 = i;
                    break;
                }
            }
            asignada.setFkidTarea(encontrado2);
                CAsignadas.create(asignada);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No fue posible asignar la tarea");
        }
    }//GEN-LAST:event_jButton9MouseReleased

    private Roles login(String usuario, String password){
        List<Usuarios> usuarios = CUsuarios.findUsuariosEntities();
        for(Usuarios i : usuarios){
            if(i.getUsuario().equals(usuario)){
               if(i.getPassword().equals(password)){
                   return i.getFkRol();
               } 
               return null;
            }
        }
        return null;
    }
    
    private void cargarComboBox(){
        List<Usuarios> usuarios = CUsuarios.findUsuariosEntities();
        List<Tareas> tareas = CTareas.findTareasEntities();
        for(Usuarios i : usuarios){
            if(i.getFkRol().getIdRol()!=1){
                barraUsuarios.addItem(i.getUsuario());
            }
        }
        for(Tareas i : tareas){
            barraTareas.addItem(i.getDescripcion());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorProyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AsignarTarea;
    private javax.swing.JTextField CampoPassword;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JPanel FormularioIngreso;
    private javax.swing.JPanel InterfazAdministrador;
    private javax.swing.JPanel Opciones;
    private javax.swing.JPanel Opciones2;
    private javax.swing.JPanel PanelCreacion;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JPanel PanelRegreso;
    private javax.swing.JPanel Salir;
    private javax.swing.JComboBox<String> barraTareas;
    private javax.swing.JComboBox<String> barraUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
