/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.prog4.isc.GestorProyectos.UI;

import co.edu.utp.prog4.isc.GestorProyectos.Controladores.ActividadesJpaController;
import co.edu.utp.prog4.isc.GestorProyectos.Controladores.AsignadasJpaController;
import co.edu.utp.prog4.isc.GestorProyectos.Controladores.ProyectosJpaController;
import co.edu.utp.prog4.isc.GestorProyectos.Controladores.TareasJpaController;
import co.edu.utp.prog4.isc.GestorProyectos.Controladores.TareasdeproyectoJpaController;
import co.edu.utp.prog4.isc.GestorProyectos.Controladores.UsuariosJpaController;
import co.edu.utp.prog4.isc.GestorProyectos.Modelo.Actividades;
import co.edu.utp.prog4.isc.GestorProyectos.Modelo.Asignadas;
import co.edu.utp.prog4.isc.GestorProyectos.Modelo.Proyectos;
import co.edu.utp.prog4.isc.GestorProyectos.Modelo.Roles;
import co.edu.utp.prog4.isc.GestorProyectos.Modelo.Tareas;
import co.edu.utp.prog4.isc.GestorProyectos.Modelo.Tareasdeproyecto;
import co.edu.utp.prog4.isc.GestorProyectos.Modelo.Usuarios;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDRES
 */
public class GestorProyectos extends javax.swing.JFrame {

    /**
     * Creates new form GestorProyectos
     */
    private UsuariosJpaController CUsuarios;
    private TareasJpaController CTareas;
    private ActividadesJpaController CActividades;
    private AsignadasJpaController CAsignadas;
    private ProyectosJpaController CProyectos;
    private TareasdeproyectoJpaController CTareasDeProyecto;
    private long tiempoInicial;
    private long tiempoFinal;
    private long diferencia;
    private long inicioSuspension;
    private long finSuspension;
    private List<Integer> suspensiones;
    private Tareas suspension;
    private Tareas tarea;
    private Usuarios usuario;
    private String contraseña;
   
    public GestorProyectos() {
        initComponents();
        CUsuarios = new UsuariosJpaController();
        CTareas = new TareasJpaController();
        CActividades = new ActividadesJpaController();
        CAsignadas = new AsignadasJpaController();
        CProyectos = new ProyectosJpaController();
        CTareasDeProyecto = new TareasdeproyectoJpaController();
        suspensiones = new ArrayList<>();
        tarea = null;
        usuario = null;
        cargarComboBox();
        this.setLocationRelativeTo(null);
        this.setSize(500, 100);
        List<Tareas> tareas = CTareas.findTareasEntities();
        for(Tareas i : tareas){
            if(i.getIdTarea()==1){
                suspension = i;
            }
        }
        cargarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        PanelLogin = new javax.swing.JPanel();
        FormularioIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CampoUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        InterfazAdministrador = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelOpciones = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Opciones = new javax.swing.JPanel();
        Opciones2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Salir = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        AsignarTarea = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PanelRegreso = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        PanelCreacion = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        barraUsuarios = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        barraTareas = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        CrearProyecto = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        nombreProyecto = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        AsignarTareaAProyecto = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        BarraProyectos = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        BarraTareas2 = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        CrearTarea = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        TFCreaTarea = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BarraProyectos2 = new javax.swing.JComboBox<>();
        jButton15 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        RealizarTarea = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jButton26 = new javax.swing.JButton();
        DescripcionPorUsuarioTarea = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        RBFinalizada = new javax.swing.JRadioButton();
        RBPendiente = new javax.swing.JRadioButton();
        jButton27 = new javax.swing.JButton();
        InterfazUsuario = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        BarraTareas3 = new javax.swing.JComboBox<>();
        jButton25 = new javax.swing.JButton();
        Consultas = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        InfoConsultas = new javax.swing.JPanel();
        PanelBlanco = new javax.swing.JPanel();
        DuracionCadaTarea = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaDuracionCadaTarea = new javax.swing.JTable();
        TotalPorSuspension = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTotalSuspension = new javax.swing.JTable();
        InversionUsuarioEnProyecto = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaInversionUsuario = new javax.swing.JTable();
        jPanel23 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        barraUsuario4 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        barraProyecto3 = new javax.swing.JComboBox<>();
        jButton28 = new javax.swing.JButton();
        Suspension = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TARazonSuspension = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        PanelLogin.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Usuario : ");
        FormularioIngreso.add(jLabel1);

        CampoUsuario.setPreferredSize(new java.awt.Dimension(100, 25));
        FormularioIngreso.add(CampoUsuario);

        jLabel2.setText("Password : ");
        FormularioIngreso.add(jLabel2);

        CampoPassword.setPreferredSize(new java.awt.Dimension(100, 25));
        CampoPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPasswordActionPerformed(evt);
            }
        });
        CampoPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoPasswordKeyTyped(evt);
            }
        });
        FormularioIngreso.add(CampoPassword);

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });
        FormularioIngreso.add(jButton1);

        PanelLogin.add(FormularioIngreso, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(PanelLogin, "card2");

        InterfazAdministrador.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Interfaz administrador");
        InterfazAdministrador.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        PanelOpciones.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Opciones");
        PanelOpciones.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        Opciones.setLayout(new java.awt.BorderLayout());

        jButton8.setText("Crear Proyecto");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton8MouseReleased(evt);
            }
        });
        Opciones2.add(jButton8);

        jButton6.setText("Crear tarea");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton6MouseReleased(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Opciones2.add(jButton6);

        jButton4.setText("Asignar tarea");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Opciones2.add(jButton4);

        jButton5.setText("Consultar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton5MouseReleased(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Opciones2.add(jButton5);

        Opciones.add(Opciones2, java.awt.BorderLayout.PAGE_END);

        PanelOpciones.add(Opciones, java.awt.BorderLayout.CENTER);

        InterfazAdministrador.add(PanelOpciones, java.awt.BorderLayout.CENTER);

        Salir.setLayout(new java.awt.BorderLayout());

        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        Salir.add(jButton3, java.awt.BorderLayout.LINE_END);

        InterfazAdministrador.add(Salir, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(InterfazAdministrador, "card3");

        AsignarTarea.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Asignacion de tareas");
        AsignarTarea.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        PanelRegreso.setLayout(new java.awt.BorderLayout());

        jButton7.setText("Regresar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton7MouseReleased(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        PanelRegreso.add(jButton7, java.awt.BorderLayout.LINE_END);

        jPanel1.add(PanelRegreso, java.awt.BorderLayout.PAGE_END);

        PanelCreacion.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Usuario ");
        jPanel2.add(jLabel6);

        barraUsuarios.setMaximumRowCount(100);
        jPanel2.add(barraUsuarios);

        jLabel7.setText("Tarea");
        jPanel2.add(jLabel7);

        barraTareas.setMaximumRowCount(100);
        barraTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraTareasActionPerformed(evt);
            }
        });
        jPanel2.add(barraTareas);

        PanelCreacion.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jButton9.setText("Confirmar Asignacion");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton9MouseReleased(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, java.awt.BorderLayout.LINE_END);

        PanelCreacion.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(PanelCreacion, java.awt.BorderLayout.CENTER);

        AsignarTarea.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(AsignarTarea, "card4");

        CrearProyecto.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Crear proyecto");
        CrearProyecto.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("Nombre del proyecto");
        jPanel6.add(jLabel9);

        nombreProyecto.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel6.add(nombreProyecto);

        jButton11.setText("Crear");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton11MouseReleased(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        CrearProyecto.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jButton13.setText("Volver");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton13MouseReleased(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13, java.awt.BorderLayout.LINE_END);

        CrearProyecto.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(CrearProyecto, "card5");

        AsignarTareaAProyecto.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        AsignarTareaAProyecto.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jButton2.setText("Volver");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jPanel10.add(jButton2, java.awt.BorderLayout.LINE_END);

        AsignarTareaAProyecto.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        jLabel10.setText("Proyecto");
        jPanel11.add(jLabel10);

        jPanel11.add(BarraProyectos);

        jLabel11.setText("Tarea");
        jPanel11.add(jLabel11);

        jPanel11.add(BarraTareas2);

        jButton12.setText("Asignar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton12MouseReleased(evt);
            }
        });
        jPanel11.add(jButton12);

        AsignarTareaAProyecto.add(jPanel11, java.awt.BorderLayout.CENTER);

        getContentPane().add(AsignarTareaAProyecto, "card6");

        CrearTarea.setLayout(new java.awt.BorderLayout());

        jLabel12.setText("Nombre de tarea");
        jPanel7.add(jLabel12);

        TFCreaTarea.setPreferredSize(new java.awt.Dimension(100, 25));
        TFCreaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCreaTareaActionPerformed(evt);
            }
        });
        jPanel7.add(TFCreaTarea);

        jLabel14.setText("Proyecto");
        jPanel7.add(jLabel14);

        jPanel7.add(BarraProyectos2);

        jButton15.setText("Crear");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton15MouseReleased(evt);
            }
        });
        jPanel7.add(jButton15);

        CrearTarea.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jButton14.setText("Volver");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton14MouseReleased(evt);
            }
        });
        jPanel12.add(jButton14, java.awt.BorderLayout.LINE_END);

        CrearTarea.add(jPanel12, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(CrearTarea, "card7");

        RealizarTarea.setLayout(new java.awt.BorderLayout());

        jPanel20.setLayout(new java.awt.BorderLayout());

        jButton26.setText("Terminar");
        jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton26MouseReleased(evt);
            }
        });
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton26, java.awt.BorderLayout.LINE_END);
        jPanel20.add(DescripcionPorUsuarioTarea, java.awt.BorderLayout.CENTER);

        RealizarTarea.add(jPanel20, java.awt.BorderLayout.PAGE_END);

        jPanel21.setLayout(new java.awt.BorderLayout());
        jPanel21.add(jPanel22, java.awt.BorderLayout.PAGE_END);

        RBFinalizada.setText("Finalizada");
        RBFinalizada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RBFinalizadaMouseReleased(evt);
            }
        });
        jPanel21.add(RBFinalizada, java.awt.BorderLayout.CENTER);

        RBPendiente.setText("Pendiente");
        RBPendiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RBPendienteMouseReleased(evt);
            }
        });
        jPanel21.add(RBPendiente, java.awt.BorderLayout.LINE_END);

        jButton27.setText("Suspender");
        jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton27MouseReleased(evt);
            }
        });
        jPanel21.add(jButton27, java.awt.BorderLayout.PAGE_START);

        RealizarTarea.add(jPanel21, java.awt.BorderLayout.CENTER);

        getContentPane().add(RealizarTarea, "card10");

        InterfazUsuario.setLayout(new java.awt.BorderLayout());

        jPanel17.setLayout(new java.awt.BorderLayout());

        jButton24.setText("Salir");
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton24MouseReleased(evt);
            }
        });
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton24, java.awt.BorderLayout.LINE_END);

        InterfazUsuario.add(jPanel17, java.awt.BorderLayout.PAGE_END);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel13.setText("Seleccione una tarea ");
        jPanel19.add(jLabel13);

        jPanel19.add(BarraTareas3);

        jButton25.setText("Confirmar");
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton25MouseReleased(evt);
            }
        });
        jPanel19.add(jButton25);

        jPanel18.add(jPanel19, java.awt.BorderLayout.PAGE_END);

        InterfazUsuario.add(jPanel18, java.awt.BorderLayout.CENTER);

        getContentPane().add(InterfazUsuario, "card9");

        Consultas.setLayout(new java.awt.BorderLayout(2, 0));

        jPanel13.setLayout(new java.awt.GridLayout(5, 0));

        jButton17.setText("Total de tiempo invertido");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton17MouseReleased(evt);
            }
        });
        jPanel13.add(jButton17);

        jButton20.setText("Total de suspenciones");
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton20MouseReleased(evt);
            }
        });
        jPanel13.add(jButton20);

        jButton21.setText("Resumen de suspensiones");
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton21MouseReleased(evt);
            }
        });
        jPanel13.add(jButton21);

        jButton16.setText("Duracion de cada tarea");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton16MouseReleased(evt);
            }
        });
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton16);

        jButton18.setText("Inversion de usuario en proyecto");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton18MouseReleased(evt);
            }
        });
        jPanel13.add(jButton18);

        Consultas.add(jPanel13, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Consultas.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        jPanel16.setLayout(new java.awt.BorderLayout());

        jButton23.setText("Volver");
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton23MouseReleased(evt);
            }
        });
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton23, java.awt.BorderLayout.LINE_END);

        Consultas.add(jPanel16, java.awt.BorderLayout.PAGE_END);

        InfoConsultas.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout PanelBlancoLayout = new javax.swing.GroupLayout(PanelBlanco);
        PanelBlanco.setLayout(PanelBlancoLayout);
        PanelBlancoLayout.setHorizontalGroup(
            PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        PanelBlancoLayout.setVerticalGroup(
            PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        InfoConsultas.add(PanelBlanco, "card3");

        DuracionCadaTarea.setLayout(new java.awt.BorderLayout());

        TablaDuracionCadaTarea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Duracion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablaDuracionCadaTarea);

        DuracionCadaTarea.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        InfoConsultas.add(DuracionCadaTarea, "card12");

        TotalPorSuspension.setLayout(new java.awt.BorderLayout());

        TablaTotalSuspension.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Proyecto", "Tiempo", "Razon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaTotalSuspension);

        TotalPorSuspension.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        InfoConsultas.add(TotalPorSuspension, "card2");

        InversionUsuarioEnProyecto.setLayout(new java.awt.BorderLayout());

        TablaInversionUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TablaInversionUsuario);

        InversionUsuarioEnProyecto.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jLabel16.setText("Usuario");
        jPanel23.add(jLabel16);

        jPanel23.add(barraUsuario4);

        jLabel17.setText("Proyecto");
        jPanel23.add(jLabel17);

        jPanel23.add(barraProyecto3);

        jButton28.setText("Filtrar");
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton28MouseReleased(evt);
            }
        });
        jPanel23.add(jButton28);

        InversionUsuarioEnProyecto.add(jPanel23, java.awt.BorderLayout.PAGE_START);

        InfoConsultas.add(InversionUsuarioEnProyecto, "card5");

        Consultas.add(InfoConsultas, java.awt.BorderLayout.CENTER);

        getContentPane().add(Consultas, "card8");

        Suspension.setLayout(new java.awt.BorderLayout());

        jLabel15.setText("A que se debe la suspension");
        Suspension.add(jLabel15, java.awt.BorderLayout.PAGE_START);

        TARazonSuspension.setColumns(20);
        TARazonSuspension.setRows(5);
        jScrollPane2.setViewportView(TARazonSuspension);

        Suspension.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jButton10.setText("Finalizar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton10MouseReleased(evt);
            }
        });
        jPanel14.add(jButton10, java.awt.BorderLayout.LINE_END);

        Suspension.add(jPanel14, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Suspension, "card11");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPasswordActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        Roles rol = null;
        rol = login(CampoUsuario.getText(),CampoPassword.getText());
        if(rol == null){
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña invalidos");
        }
        else{
            if(rol.getIdRol()==1){
                CampoUsuario.setText("");
                CampoPassword.setText("");
                JOptionPane.showMessageDialog(null, "Ingreso de administrador");
                PanelLogin.setVisible(false);
                this.setSize(600, 150);
                InterfazAdministrador.setVisible(true);
            }
            if(rol.getIdRol()==2){
                JOptionPane.showMessageDialog(null, "Ingreso de ususario");
                cargarComboBoxTareas();
                CampoUsuario.setText("");
                CampoPassword.setText("");
                PanelLogin.setVisible(false);
                this.setSize(400, 150);
                InterfazUsuario.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        InterfazAdministrador.setVisible(false);
        PanelLogin.setVisible(true);
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseReleased
        InterfazAdministrador.setVisible(false);
        this.setSize(400, 150);
        AsignarTarea.setVisible(true);
    }//GEN-LAST:event_jButton4MouseReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseReleased
        AsignarTarea.setVisible(false);
        InterfazAdministrador.setVisible(true);
        this.setSize(600, 150);
    }//GEN-LAST:event_jButton7MouseReleased

    private void jButton9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseReleased
        try {
            Asignadas asignada = new Asignadas();
            List<Usuarios> usuarios = CUsuarios.findUsuariosEntities();
            Usuarios encontrado = null;
            for(Usuarios i : usuarios){
                if(((String)barraUsuarios.getSelectedItem()).equals(i.getUsuario())){
                    encontrado = i;
                    break;
                }
            }
            System.out.println((String)barraUsuarios.getSelectedItem());
            asignada.setFkUsu(encontrado);
            List<Tareas> tareas = CTareas.findTareasEntities();
            Tareas encontrado2 = null;
            for(Tareas i : tareas){
                if(((String)barraTareas.getSelectedItem()).equals(i.getDescripcion())){
                    encontrado2 = i;
                    break;
                }
            }
            List<Tareasdeproyecto> tareasProyectos = CTareasDeProyecto.findTareasdeproyectoEntities();
            Proyectos encontrado3 = null;
            for(Tareasdeproyecto i : tareasProyectos){
                if(i.getFkidTarea2().equals(encontrado2)){
                    encontrado3 = i.getFkidPro();
                }
            }
            asignada.setFkidTarea(encontrado2);
            asignada.setTerminado(false);
            asignada.setFkidPro(encontrado3);
            CAsignadas.create(asignada);
            JOptionPane.showMessageDialog(null, "Tarea asignada exitosamente");
            AsignarTarea.setVisible(false);
            InterfazAdministrador.setVisible(true);
            this.setSize(600,150);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No fue posible asignar la tarea");
        }
    }//GEN-LAST:event_jButton9MouseReleased

    private void jButton8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseReleased
        InterfazAdministrador.setVisible(false);
        CrearProyecto.setVisible(true);
        this.setSize(400,150);
    }//GEN-LAST:event_jButton8MouseReleased

    private void jButton11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseReleased
        try{
            Proyectos proyecto = new Proyectos();
            proyecto.setNombreProyecto(nombreProyecto.getText());
            CProyectos.create(proyecto);
            nombreProyecto.setText("");
            JOptionPane.showMessageDialog(null, "Proyecto creado exitosamente");
            CrearProyecto.setVisible(false);
            InterfazAdministrador.setVisible(true);
            this.setSize(600,150);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "No se pudo crear el proyecto");
        }
        
    }//GEN-LAST:event_jButton11MouseReleased

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseReleased
        CrearProyecto.setVisible(false);
        InterfazAdministrador.setVisible(true);
        this.setSize(600,150);
    }//GEN-LAST:event_jButton13MouseReleased

    private void jButton12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseReleased
        try{
            Tareasdeproyecto tareaDeProyecto = new Tareasdeproyecto();
            tareaDeProyecto.setFkidPro((Proyectos)BarraProyectos.getSelectedItem());
            tareaDeProyecto.setFkidTarea2((Tareas)BarraTareas2.getSelectedItem());
            CTareasDeProyecto.create(tareaDeProyecto);
            JOptionPane.showMessageDialog(null, "Tarea asignada a proyecto exitosamente");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "No fue posible asignar la tarea al proyecto" + e);
        }
        
    }//GEN-LAST:event_jButton12MouseReleased

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        AsignarTareaAProyecto.setVisible(false);
        InterfazAdministrador.setVisible(true);
    }//GEN-LAST:event_jButton2MouseReleased

    private void TFCreaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCreaTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCreaTareaActionPerformed

    private void jButton14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseReleased
        CrearTarea.setVisible(false);
        InterfazAdministrador.setVisible(true);
    }//GEN-LAST:event_jButton14MouseReleased

    private void jButton6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseReleased
        CrearTarea.setVisible(true);
        InterfazAdministrador.setVisible(false);
    }//GEN-LAST:event_jButton6MouseReleased

    private void jButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseReleased
        InterfazAdministrador.setVisible(false);
        Consultas.setVisible(true);
        this.setSize(600,400);
        this.setTitle("Consultas");
    }//GEN-LAST:event_jButton5MouseReleased

    private void jButton17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseReleased
        int tiempoTotal = 0;
        List<Actividades> actividades = CActividades.findActividadesEntities();
        for(Actividades i : actividades){
            tiempoTotal += i.getTiempo();
        }
        String mensaje;
        mensaje = "El tiempo invertido en el proyecto fue de : " + Integer.toString(tiempoTotal) + " segundos";
        JOptionPane.showMessageDialog(null,mensaje);
    }//GEN-LAST:event_jButton17MouseReleased

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton23MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseReleased
        Consultas.setVisible(false);
        InterfazAdministrador.setVisible(true);
        this.setTitle("Interfaz Administrador");
        this.setSize(600,150);
    }//GEN-LAST:event_jButton23MouseReleased

    private void jButton20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseReleased
        int suspensiones = 0;
        List<Actividades> actividades = CActividades.findActividadesEntities();
        for(Actividades i : actividades){
            if(i.getFkidTarea().getIdTarea()==1){
                suspensiones++;
            }
        }
        String mensaje = "El total de suspensiones fueron : " + Integer.toString(suspensiones);
        JOptionPane.showMessageDialog(null, mensaje);
    }//GEN-LAST:event_jButton20MouseReleased

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton24MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseReleased
        InterfazUsuario.setVisible(false);
        PanelLogin.setVisible(true);
        this.setSize(500,100);
        BarraTareas3.removeAllItems();
    }//GEN-LAST:event_jButton24MouseReleased

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton25MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseReleased
        List<Tareas> tareas = CTareas.findTareasEntities();
        String tareaT = (String)BarraTareas3.getSelectedItem();
        Tareas encontrada = null;
        for(Tareas i : tareas){
            if(i.getDescripcion().equals(tareaT)){
                tarea = i;
            }
        }
        InterfazUsuario.setVisible(false);
        RealizarTarea.setVisible(true);
        tiempoInicial = System.currentTimeMillis();
        RBPendiente.setSelected(true);
    }//GEN-LAST:event_jButton25MouseReleased

    private void RBFinalizadaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBFinalizadaMouseReleased
        RBPendiente.setSelected(false);
        if(!RBFinalizada.isSelected()){
            RBFinalizada.setSelected(true);
        }
    }//GEN-LAST:event_RBFinalizadaMouseReleased

    private void RBPendienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBPendienteMouseReleased
        RBFinalizada.setSelected(false);
        if(!RBPendiente.isSelected()){
            RBPendiente.setSelected(true);
        }
    }//GEN-LAST:event_RBPendienteMouseReleased

    private void jButton26MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseReleased
        Actividades actividad = new Actividades();
        tiempoFinal = System.currentTimeMillis();
        diferencia = (tiempoFinal - tiempoInicial)/1000;
        String descripcion = DescripcionPorUsuarioTarea.getText();
        Proyectos proyecto = null;
        List<Tareasdeproyecto> tareasDeProyecto = CTareasDeProyecto.findTareasdeproyectoEntities();
        for(Tareasdeproyecto i : tareasDeProyecto){
            if(i.getFkidTarea2().equals(tarea)){
                proyecto = i.getFkidPro();
            }
        }
        actividad.setDescripcion(descripcion);
        actividad.setFkUsu(usuario);
        actividad.setFkidPro2(proyecto);
        actividad.setFkidTarea(tarea);
        for(int i : suspensiones){
            diferencia -= i;    
        }
        suspensiones.clear();
        actividad.setTiempo((int)diferencia);
        CActividades.create(actividad);
        if(RBFinalizada.isSelected()){
            List<Asignadas> asignadas = CAsignadas.findAsignadasEntities();
            for(Asignadas i : asignadas){
                if(i.getFkUsu().equals(usuario)&&i.getFkidPro().equals(proyecto)&&i.getFkidTarea().equals(tarea)){
                    Asignadas edit = i;
                    edit.setTerminado(true);
                    try {
                        CAsignadas.edit(edit);
                    } catch (Exception ex) {
                        Logger.getLogger(GestorProyectos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        RealizarTarea.setVisible(false);
        InterfazUsuario.setVisible(true);
    }//GEN-LAST:event_jButton26MouseReleased

    private void jButton15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseReleased
        Tareas tarea = new Tareas();
        tarea.setDescripcion(TFCreaTarea.getText());
        List<Proyectos> proyectos = CProyectos.findProyectosEntities();
        Proyectos encontrado = null;
        for(Proyectos i : proyectos){
            if(i.getNombreProyecto().equals(BarraProyectos2.getSelectedItem())){
                encontrado = i;
                break;
            }
        }
        CTareas.create(tarea);
        CrearTarea.setVisible(false);
        InterfazAdministrador.setVisible(true);
        Tareasdeproyecto tareaAsignada = new Tareasdeproyecto();
        tareaAsignada.setFkidPro(encontrado);
        tareaAsignada.setFkidTarea2(tarea);
        CTareasDeProyecto.create(tareaAsignada);
    }//GEN-LAST:event_jButton15MouseReleased

    private void jButton21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseReleased
        mostrarPanelBlanco();
        PanelBlanco.setVisible(false);
        TotalPorSuspension.setVisible(true);
    }//GEN-LAST:event_jButton21MouseReleased

    private void barraTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraTareasActionPerformed

    private void jButton27MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseReleased
        RealizarTarea.setVisible(false);
        Suspension.setVisible(true);
        inicioSuspension = System.currentTimeMillis();
    }//GEN-LAST:event_jButton27MouseReleased

    private void jButton10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseReleased
        finSuspension = System.currentTimeMillis();
        Actividades actividad = new Actividades();
        List<Asignadas> asignadas = CAsignadas.findAsignadasEntities();
        Proyectos asignada = null;
        for(Asignadas i : asignadas){
            if(i.getFkidTarea().equals(tarea)){
                asignada = i.getFkidPro();
            }
        }
        actividad.setFkUsu(usuario);
        actividad.setFkidPro2(asignada);
        actividad.setFkidTarea(suspension);
        actividad.setDescripcion(TARazonSuspension.getText());
        int tiempo = (int)((finSuspension-inicioSuspension)/1000);
        suspensiones.add(tiempo);
        actividad.setTiempo(tiempo);
        CActividades.create(actividad);
        RealizarTarea.setVisible(true);
        Suspension.setVisible(false);
    }//GEN-LAST:event_jButton10MouseReleased

    private void jButton16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseReleased
        mostrarPanelBlanco();
        PanelBlanco.setVisible(false);
        DuracionCadaTarea.setVisible(true);
    }//GEN-LAST:event_jButton16MouseReleased

    private void jButton28MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseReleased
        DefaultTableModel modelo = (DefaultTableModel) TablaInversionUsuario.getModel();
        modelo.setRowCount(0);
        List<Usuarios> usuarios = CUsuarios.findUsuariosEntities();
        List<Proyectos> proyectos = CProyectos.findProyectosEntities();
        List<Tareas> tareas = CTareas.findTareasEntities();
        List<Actividades> actividades = CActividades.findActividadesEntities();
        Usuarios encontrado = null;
        for(Usuarios i : usuarios){
            if(i.getUsuario().equals(barraUsuario4.getSelectedItem())){
                encontrado = i;
            }
        }
        Proyectos encontrado2 = null;
        for(Proyectos i : proyectos){
            if(i.getNombreProyecto().equals(barraProyecto3.getSelectedItem())){
                encontrado2 = i;
            }
        }
        for(Tareas i : tareas){
            if(i.getIdTarea()!=1){
                int cont = 0;
                for(Actividades j : actividades){
                    if(j.getFkUsu().equals(encontrado)&&j.getFkidPro2().equals(encontrado2)&&j.getFkidTarea().equals(i)){
                        cont+=j.getTiempo();
                    }
                }
                Object registro[] = {i.getDescripcion(),cont};
                modelo.addRow(registro);
            }
        }
    }//GEN-LAST:event_jButton28MouseReleased

    private void jButton18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseReleased
        mostrarPanelBlanco();
        PanelBlanco.setVisible(false);
        InversionUsuarioEnProyecto.setVisible(true);
    }//GEN-LAST:event_jButton18MouseReleased

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void CampoPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoPasswordKeyPressed

    }//GEN-LAST:event_CampoPasswordKeyPressed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased

    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped

    }//GEN-LAST:event_jButton1KeyTyped

    private void CampoPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoPasswordKeyReleased

    }//GEN-LAST:event_CampoPasswordKeyReleased

    private void CampoPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoPasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPasswordKeyTyped

    private Roles login(String usuario, String password){
        List<Usuarios> usuarios = CUsuarios.findUsuariosEntities();
        for(Usuarios i : usuarios){
            if(i.getUsuario().equals(usuario)){
               if(i.getPassword().equals(password)){
                   this.usuario = i;
                   return i.getFkRol();
               } 
               return null;
            }
        }
        return null;
    }
    
    private void cargarComboBox(){
        List<Usuarios> usuarios = CUsuarios.findUsuariosEntities();
        List<Tareas> tareas = CTareas.findTareasEntities();
        List<Proyectos> proyectos = CProyectos.findProyectosEntities();
        for(Usuarios i : usuarios){
            if(i.getFkRol().getIdRol()!=1){
                barraUsuarios.addItem(i.getUsuario());
                barraUsuario4.addItem(i.getUsuario());
            }
        }
        for(Tareas i : tareas){
            if(i.getIdTarea()!=1){
                barraTareas.addItem(i.getDescripcion());
                BarraTareas2.addItem(i.getDescripcion());
            }
        }
        for(Proyectos i : proyectos){
            BarraProyectos.addItem(i.getNombreProyecto());
            BarraProyectos2.addItem(i.getNombreProyecto());
            barraProyecto3.addItem(i.getNombreProyecto());
        }
    }
    
    public void mostrarPanelBlanco(){
        PanelBlanco.setVisible(true);
        DuracionCadaTarea.setVisible(false);
        TotalPorSuspension.setVisible(false);
    }
    
    public void cargarTablas(){
        List<Actividades> actividades = CActividades.findActividadesEntities();
        int num = 0;
        for(Actividades i : actividades){
            if(i.getFkidTarea().getIdTarea()==1){
                DefaultTableModel modelo = (DefaultTableModel) TablaTotalSuspension.getModel();
                Object registro[] = {i.getFkUsu().getUsuario(),i.getFkidPro2().getNombreProyecto(),i.getTiempo(),i.getDescripcion()};
                modelo.addRow(registro);
            }
        }
        DefaultTableModel modelo = (DefaultTableModel) TablaDuracionCadaTarea.getModel();
        List<Tareas> tareas = CTareas.findTareasEntities();
        for(Tareas i : tareas){
            if(i.getIdTarea()!=1){
                int cont = 0;
                for(Actividades j : actividades){
                    if(i.equals(j.getFkidTarea())){
                        cont+=j.getTiempo();
                    }
                }
                Object registro[] = {i.getDescripcion(),cont};
                modelo.addRow(registro);
            } 
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorProyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AsignarTarea;
    private javax.swing.JPanel AsignarTareaAProyecto;
    private javax.swing.JComboBox<String> BarraProyectos;
    private javax.swing.JComboBox<String> BarraProyectos2;
    private javax.swing.JComboBox<String> BarraTareas2;
    private javax.swing.JComboBox<String> BarraTareas3;
    private javax.swing.JTextField CampoPassword;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JPanel Consultas;
    private javax.swing.JPanel CrearProyecto;
    private javax.swing.JPanel CrearTarea;
    private javax.swing.JTextField DescripcionPorUsuarioTarea;
    private javax.swing.JPanel DuracionCadaTarea;
    private javax.swing.JPanel FormularioIngreso;
    private javax.swing.JPanel InfoConsultas;
    private javax.swing.JPanel InterfazAdministrador;
    private javax.swing.JPanel InterfazUsuario;
    private javax.swing.JPanel InversionUsuarioEnProyecto;
    private javax.swing.JPanel Opciones;
    private javax.swing.JPanel Opciones2;
    private javax.swing.JPanel PanelBlanco;
    private javax.swing.JPanel PanelCreacion;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JPanel PanelRegreso;
    private javax.swing.JRadioButton RBFinalizada;
    private javax.swing.JRadioButton RBPendiente;
    private javax.swing.JPanel RealizarTarea;
    private javax.swing.JPanel Salir;
    private javax.swing.JPanel Suspension;
    private javax.swing.JTextArea TARazonSuspension;
    private javax.swing.JTextField TFCreaTarea;
    private javax.swing.JTable TablaDuracionCadaTarea;
    private javax.swing.JTable TablaInversionUsuario;
    private javax.swing.JTable TablaTotalSuspension;
    private javax.swing.JPanel TotalPorSuspension;
    private javax.swing.JComboBox<String> barraProyecto3;
    private javax.swing.JComboBox<String> barraTareas;
    private javax.swing.JComboBox<String> barraUsuario4;
    private javax.swing.JComboBox<String> barraUsuarios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nombreProyecto;
    // End of variables declaration//GEN-END:variables

    private void cargarComboBoxTareas() {
        List<Asignadas> asignadas = CAsignadas.findAsignadasEntities();
        for(Asignadas i : asignadas){
            System.out.println(i.getFkUsu().getUsuario());
            System.out.println(usuario.getUsuario());
            if(i.getFkUsu().getUsuario().equals(usuario.getUsuario())&&!i.getTerminado()){
                BarraTareas3.addItem(i.getFkidTarea().getDescripcion());
            }
        }
    }
}
